[package]
name = "alchemy"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
printpdf = "0.7.0"
serde_json = "1.0.133"
uuid = { version = "1.11.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
